language: ruby

rvm:
  - 2.1
  - 2.2

before_install:
  - gem install bundler

gemfile: ci.gemfile

env:
  - CHEF_VERSION="master"
  - CHEF_VERSION="~> 12.0"
  - CHEF_VERSION="< 12"

matrix:
  exclude:
  - rvm: 2.1
    env: CHEF_VERSION="master"
  - rvm: 2.1
    env: CHEF_VERSION="~> 12.0"

branches:
  only:
  - master
