language: ruby
cache: bundler
dist: xenial
sudo: false

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - ruby-head

before_install:
  - gem install bundler

gemfile: ci.gemfile

env:
  - CHEF_VERSION="master"
  - CHEF_VERSION="~> 14.0"
  - CHEF_VERSION="~> 13.0"

matrix:
  exclude:
  - rvm: 2.3.8
    env: CHEF_VERSION="master"
  - rvm: 2.3.8
    env: CHEF_VERSION="~> 14.0"
  - rvm: 2.4.5
    env: CHEF_VERSION="master"
  allow_failures:
    - rvm: ruby-head

branches:
  only:
  - master
