version: "master-{build}"

os: Windows Server 2012
platform:
  - x64

environment:
  bundle_gemfile: ci.gemfile

  matrix:
    - ruby_version: "193"
      chef_version: "< 12"

    - ruby_version: "200"
      chef_version: "< 12"

    - ruby_version: "200"
      chef_version: "~> 12.0"

    - ruby_version: "200"
      chef_version: "master"

clone_folder: c:\projects\knife-windows
clone_depth: 1
branches:
  only:
    - master

init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - winrm quickconfig -q
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - echo %PATH%
  - ruby --version
  - gem --version
  - gem install bundler --quiet --no-ri --no-rdoc
  - bundler --version

build_script:
  - bundle install || bundle install || bundle install

test_script:
  - bundle exec rake

on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))