version: "master-{build}"

os: Windows Server 2012
platform:
  - x64

environment:
  bundle_gemfile: ci.gemfile

  matrix:
    - ruby_version: "20"
      chef_version: "< 12"

    - ruby_version: "21"
      chef_version: "~> 12.0"

    - ruby_version: "21"
      chef_version: "master"

clone_folder: c:\projects\knife-windows
clone_depth: 1
branches:
  only:
    - master

install:
  - winrm quickconfig -q
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - echo %PATH%
  - ruby --version
  - gem --version
  - gem install bundler -v 1.11.2 --quiet --no-ri --no-rdoc
  - bundler --version

build_script:
  - bundle install || bundle install || bundle install

test_script:
  - bundle exec rake
